version: '3.4'

services:
  crud.api:
    container_name: API
    image: ${DOCKER_REGISTRY-}crudapi
    build:
      context: .
      dockerfile: CRUD.API/Dockerfile
    networks:
      - mynetwork
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge